import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import "./globals.css";

import { Geist } from 'next/font/google';
 
const font = Geist({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className}`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
